### ISSUE TITLE
x86 support 

### ISSUE THREAD

**Issue by nOmi7** [Jamol/kuma#10]
How can i compile this project to support android x86 or any other abi for that matter.
I tried generating openssl libs for x86 and put it in vendor folder however it did not work.
It keeps on giving errors like undefined references to few BIO_* and X503_*

**Comment by Jamol** [comment]
you can try this cmd: ndk-build APP_ABI=x86

**Comment by Jamol** [comment]
fixed

**Comment by nOmi7** [comment]
Cool thanks :)
