### ISSUE TITLE
No Luck compiling with OpenSSL

### ISSUE THREAD

**Issue by ibroheem** [Jamol/kuma#2]
I use:
- GCC 6.3.0
- OpenSSL 1.1.0k

When the Option KUMA_HAS_OPENSSL is turned on I run into error:
`In file included from ssl/SslHandler.cpp:27:0:
./../vendor/openssl/include/openssl/x509v3.h:155:1: error: expected constructor, destructor, or type conversion before ‘typedef’
 typedef BIT_STRING_BITNAME ENUMERATED_NAMES;
 ^~~~~~~
./../vendor/openssl/include/openssl/x509v3.h:221:1: error: expected constructor, destructor, or type conversion before ‘DECLARE_ASN1_SET_OF’
 DECLARE_ASN1_SET_OF(GENERAL_NAME)
 ^~~~~~~~~~~~~~~~~~~
ssl/SslHandler.cpp:124:1: error: expected ‘}’ at end of input
 }
 ^
Makefile:93: recipe for target '../objs/linux/ssl/SslHandler.o' failed
make: *** [../objs/linux/ssl/SslHandler.o] Error 1
`

Help needed pls:
 - compiler used
 - OpenSSL version etc

**Comment by Jamol** [comment]
thanks for reporting the issue, will try to reproduce it later

**Comment by Jamol** [comment]
fixed on commit https://github.com/Jamol/kuma/commit/90b4c12700da47678fbf9fe839b4d391041ec048

**Comment by Jamol** [comment]
verified on: openssl 1.1.1 and GCC 5.4.0

**Comment by ibroheem** [comment]
Will try it out and give you feedback!
