### ISSUE TITLE
node.js return error "RangeError: Invalid WebSocket frame: MASK must be set"

### ISSUE THREAD

**Issue by schyjxy** [Jamol/kuma#31]
The proggram runned on ubuntu,  and the sever throw error "RangeError: Invalid WebSocket frame: MASK must be set"  and exited.

**Comment by Jamol** [comment]
Do you use ws as websocket server? The following link maybe help:
https://github.com/websockets/ws/issues/1315

**Comment by schyjxy** [comment]
I found the the reason is that KBuffer was not properly initialized
`int WsClient::sendData(const uint8_t *data, uint32_t len){
    KMBuffer buffer;
    buffer.write(data, len);
    return ws->send(buffer, true, true);
 }`
