### ISSUE TITLE
SSL_ERROR

### ISSUE THREAD

**Issue by clearsky** [Jamol/kuma#35]
![image](https://user-images.githubusercontent.com/38609798/152642509-5a4f89bc-b4f2-4455-810b-fcb4f835a83e.png)
http is ok, but https always returns -15

**Comment by Jamol** [comment]
For HTTPS request, the CA certs of the target site must be copied to path-to-your-excutable/cert/ca.pem. You can get the site CA cert from browser.

**Comment by codenot** [comment]
why we need ca cert？  we only are client.

**Comment by Jamol** [comment]
Enhanced by PR #37

**Comment by a572651459** [comment]
> 
I have obtained the certificate of www.baidu.com , but the error in the figure still appears
![image](https://user-images.githubusercontent.com/34877312/196649978-e33a98c8-676d-44ba-b2e8-afcfc427243e.png)
