### ISSUE TITLE
Linux make err：

### ISSUE THREAD

**Issue by zsy86111** [Jamol/kuma#36]
Linux：
cd src
make

Errors：
g++: error: ../third_party/libkev/lib/linux/Release/libkev.a: No such file or directory
g++: error: ../third_party/libkev/lib/linux/Release/libkev.a: No such file or directory

**Comment by Jamol** [comment]
The dependency libkev is not built, you can run the build script ./bld/linux/build_linux.py instead of Makefile.
NOTE: cmake is required to build libkev
