### ISSUE TITLE
buildRequestHeaders didn't make path well.

### ISSUE THREAD

**Issue by superzmy** [Jamol/kuma#40]
H2StreamProxy.cpp : buildRequestHeaders()
The git old version discard the path part, so that I get 400 bad request.
------from----------
    std::string path = uri_.getPath();
    if(!uri_.getQuery().empty()) {
        path = "?" + uri_.getQuery();
    }
    if(!uri_.getFragment().empty()) {
        path = "#" + uri_.getFragment();
    }
--------to--------
    std::string path = uri_.getPath();
    if(!uri_.getQuery().empty()) {
        path += "?";
        path += uri_.getQuery();
    }
    if(!uri_.getFragment().empty()) {
        path += "#";
        path += uri_.getFragment();
    }
----------------

**Comment by Jamol** [comment]
Hi, ZMY, thanks for the report.
Which platform are you testing on?

**Comment by superzmy** [comment]
windows，http/2。
header string lose the path part , like:
www.xxx.com/abc/efg?x=11111
to 
www.xxx.com/?x=11111

**Comment by Jamol** [comment]
you are right, it is fixed, thanks.
