### ISSUE TITLE
it seems that no way to set Http2 connection with timeout

### ISSUE THREAD

**Issue by superzmy** [Jamol/kuma#41]
while TcpSocket::Impl::connect has timeout_ms arg,
but TcpConnection didn't pass this arg.

close() outside seems useless when connecting.
```
    // http is kuma::HttpRequest
    std::function<void()> fReconnect = [&] {
        puts("Reconnect");
        http.close();
        http.sendRequest("GET", "https://xxxxxxxxxxxx/");
        timerReconnect.schedule(1000, Timer::Mode::ONE_SHOT, fReconnect);
    };
    timerReconnect.schedule(1000, Timer::Mode::ONE_SHOT, fReconnect);
```

I had to insert this code into SocketBase::connect
```
    if (timeout_ms == 0)
        timeout_ms = 100;
```
and then it seems better to quick reconnect.

**Comment by superzmy** [comment]
totally I need a way to http2 sendRquest(...) in a not very good network, sometimes it lose packet so connect will wait seconds until timeout, but if recall after 100ms it may success quickly.
Now the kuma::HttpRequest::close() and sendRequest in timer seems useless.
And even I force SocketBase::connect timeout_ms to 100ms and close&sendRequest after first400ms is no response come, In rare cases I wait many seconds to get first error Callback and after then the close&sendRequest can tack effect.
So is someway to force destroy socket of HTTP2 in any situation and reconnect?

**Comment by Jamol** [comment]
Now H2Connection::getConnection is ready to get underlying connection for http2 request, and you can close it with returned connection
