### ISSUE TITLE
make android lib error

### ISSUE THREAD

**Issue by BadDeveloper2022** [Jamol/kuma#42]
-- Build files have been written to: /root/code/kuma/bld/android/out/armeabi-v7a
[  1%] Building CXX object CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
[  2%] Building CXX object CMakeFiles/kuma.dir/src/DnsResolver.cpp.o
[  4%] Building CXX object CMakeFiles/kuma.dir/src/SocketBase.cpp.o
[  5%] Building CXX object CMakeFiles/kuma.dir/src/TcpConnection.cpp.o
[  7%] Building CXX object CMakeFiles/kuma.dir/src/TcpListenerImpl.cpp.o
[  8%] Building CXX object CMakeFiles/kuma.dir/src/TcpSocketImpl.cpp.o
[ 10%] Building CXX object CMakeFiles/kuma.dir/src/UdpSocketBase.cpp.o
[ 11%] Building CXX object CMakeFiles/kuma.dir/src/UdpSocketImpl.cpp.o
[ 13%] Building CXX object CMakeFiles/kuma.dir/src/compr/compr.cpp.o
[ 14%] Building CXX object CMakeFiles/kuma.dir/src/compr/compr_zlib.cpp.o
[ 16%] Building CXX object CMakeFiles/kuma.dir/src/http/H1xStream.cpp.o
[ 17%] Building CXX object CMakeFiles/kuma.dir/src/http/Http1xRequest.cpp.o
[ 19%] Building CXX object CMakeFiles/kuma.dir/src/http/Http1xResponse.cpp.o
[ 20%] Building CXX object CMakeFiles/kuma.dir/src/http/HttpCache.cpp.o
[ 22%] Building CXX object CMakeFiles/kuma.dir/src/http/HttpHeader.cpp.o
[ 23%] Building CXX object CMakeFiles/kuma.dir/src/http/HttpMessage.cpp.o
[ 25%] Building CXX object CMakeFiles/kuma.dir/src/http/HttpParserImpl.cpp.o
[ 26%] Building CXX object CMakeFiles/kuma.dir/src/http/HttpRequestImpl.cpp.o
[ 28%] Building CXX object CMakeFiles/kuma.dir/src/http/HttpResponseImpl.cpp.o
[ 29%] Building CXX object CMakeFiles/kuma.dir/src/http/Uri.cpp.o
[ 31%] Building CXX object CMakeFiles/kuma.dir/src/http/httputils.cpp.o
[ 32%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/FlowControl.cpp.o
[ 34%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/FrameParser.cpp.o
[ 35%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/H2ConnectionImpl.cpp.o
[ 37%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/H2ConnectionMgr.cpp.o
[ 38%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/H2Frame.cpp.o
[ 40%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/H2Handshake.cpp.o
[ 41%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/H2Stream.cpp.o
[ 43%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/H2StreamProxy.cpp.o
[ 44%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/Http2Request.cpp.o
[ 46%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/Http2Response.cpp.o
[ 47%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/PushClient.cpp.o
[ 49%] Building CXX object CMakeFiles/kuma.dir/src/http/v2/h2utils.cpp.o
[ 50%] Building CXX object CMakeFiles/kuma.dir/src/kmapi.cpp.o
[ 52%] Building CXX object CMakeFiles/kuma.dir/src/proxy/BasicAuthenticator.cpp.o
[ 53%] Building CXX object CMakeFiles/kuma.dir/src/proxy/ProxyAuthenticator.cpp.o
[ 55%] Building CXX object CMakeFiles/kuma.dir/src/proxy/ProxyConnectionImpl.cpp.o
[ 56%] Building CXX object CMakeFiles/kuma.dir/src/utils/base64.cpp.o
[ 58%] Building CXX object CMakeFiles/kuma.dir/src/utils/utils.cpp.o
[ 59%] Building CXX object CMakeFiles/kuma.dir/src/ws/WSConnection.cpp.o
[ 61%] Building CXX object CMakeFiles/kuma.dir/src/ws/WSConnection_v1.cpp.o
[ 62%] Building CXX object CMakeFiles/kuma.dir/src/ws/WSConnection_v2.cpp.o
[ 64%] Building CXX object CMakeFiles/kuma.dir/src/ws/WSHandler.cpp.o
[ 65%] Building CXX object CMakeFiles/kuma.dir/src/ws/WebSocketImpl.cpp.o
[ 67%] Building CXX object CMakeFiles/kuma.dir/src/ws/exts/ExtensionHandler.cpp.o
[ 68%] Building CXX object CMakeFiles/kuma.dir/src/ws/exts/PMCE_Base.cpp.o
[ 70%] Building CXX object CMakeFiles/kuma.dir/src/ws/exts/PMCE_Deflate.cpp.o
[ 71%] Building CXX object CMakeFiles/kuma.dir/src/ws/exts/WSExtension.cpp.o
[ 73%] Building C object CMakeFiles/kuma.dir/third_party/zlib/adler32.c.o
[ 74%] Building C object CMakeFiles/kuma.dir/third_party/zlib/compress.c.o
[ 76%] Building C object CMakeFiles/kuma.dir/third_party/zlib/crc32.c.o
[ 77%] Building C object CMakeFiles/kuma.dir/third_party/zlib/deflate.c.o
[ 79%] Building C object CMakeFiles/kuma.dir/third_party/zlib/infback.c.o
[ 80%] Building C object CMakeFiles/kuma.dir/third_party/zlib/inffast.c.o
[ 82%] Building C object CMakeFiles/kuma.dir/third_party/zlib/inflate.c.o
[ 83%] Building C object CMakeFiles/kuma.dir/third_party/zlib/inftrees.c.o
[ 85%] Building C object CMakeFiles/kuma.dir/third_party/zlib/trees.c.o
[ 86%] Building C object CMakeFiles/kuma.dir/third_party/zlib/uncompr.c.o
[ 88%] Building C object CMakeFiles/kuma.dir/third_party/zlib/zutil.c.o
[ 89%] Building CXX object CMakeFiles/kuma.dir/third_party/HPacker/src/HPackTable.cpp.o
[ 91%] Building CXX object CMakeFiles/kuma.dir/third_party/HPacker/src/HPacker.cpp.o
[ 92%] Building CXX object CMakeFiles/kuma.dir/src/ssl/BioHandler.cpp.o
[ 94%] Building CXX object CMakeFiles/kuma.dir/src/ssl/OpenSslLib.cpp.o
[ 95%] Building CXX object CMakeFiles/kuma.dir/src/ssl/SioHandler.cpp.o
[ 97%] Building CXX object CMakeFiles/kuma.dir/src/ssl/SslHandler.cpp.o
[ 98%] Building CXX object CMakeFiles/kuma.dir/src/ssl/ssl_utils_linux.cpp.o
[100%] Linking CXX shared library ../../../../bin/android/armeabi-v7a/libkuma.so
ld: error: relocation R_ARM_REL32 cannot be used against symbol 'kev::KMObject::KMObject()::s_objIdSeed'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::Impl(kev::PollType)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'construction vtable for std::__ndk1::basic_istream<char, std::__ndk1::char_traits<char> >-in-std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::Impl(kev::PollType)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::Impl(kev::PollType)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for std::__ndk1::__shared_ptr_pointer<kev::TimerManager*, std::__ndk1::default_delete<kev::TimerManager>, std::__ndk1::allocator<kev::TimerManager> >'; recompile with -fPIC
>>> defined in /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a(EventLoopImpl.cpp.o)
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::Impl(kev::PollType)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for std::__ndk1::basic_stringbuf<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::Impl(kev::PollType)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'VTT for std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::Impl(kev::PollType)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'VTT for std::__ndk1::basic_stringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::Impl(kev::PollType)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for std::__ndk1::__shared_ptr_emplace<kev::DLQueue<std::__ndk1::function<void (kev::LoopActivity)> >::DLNode, std::__ndk1::allocator<kev::DLQueue<std::__ndk1::function<void (kev::LoopActivity)> >::DLNode> >'; recompile with -fPIC
>>> defined in /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a(EventLoopImpl.cpp.o)
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(std::__ndk1::shared_ptr<kev::DLQueue<std::__ndk1::function<void (kev::LoopActivity)> >::DLNode> kev::DLQueue<std::__ndk1::function<void (kev::LoopActivity)> >::enqueue<std::__ndk1::function<void (kev::LoopActivity)> >(std::__ndk1::function<void (kev::LoopActivity)>&&)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'construction vtable for std::__ndk1::basic_ostream<char, std::__ndk1::char_traits<char> >-in-std::__ndk1::basic_ostringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::loop(unsigned int)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for std::__ndk1::basic_ostringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::loop(unsigned int)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for std::__ndk1::basic_stringbuf<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::loop(unsigned int)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'VTT for std::__ndk1::basic_ostringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::loop(unsigned int)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'VTT for std::__ndk1::basic_ostringstream<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >'; recompile with -fPIC
>>> defined in CMakeFiles/kuma.dir/src/AcceptorBase.cpp.o
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::loop(unsigned int)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for std::__ndk1::__shared_ptr_emplace<kev::TokenTaskSlot, std::__ndk1::allocator<kev::TokenTaskSlot> >'; recompile with -fPIC
>>> defined in /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a(EventLoopImpl.cpp.o)
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::appendTask(std::__ndk1::function<void ()>, kev::EventLoop::Token::Impl*, char const*)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for kev::TaskSlot'; recompile with -fPIC
>>> defined in /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a(EventLoopImpl.cpp.o)
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::appendTask(std::__ndk1::function<void ()>, kev::EventLoop::Token::Impl*, char const*)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for kev::TokenTaskSlot'; recompile with -fPIC
>>> defined in /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a(EventLoopImpl.cpp.o)
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::appendTask(std::__ndk1::function<void ()>, kev::EventLoop::Token::Impl*, char const*)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for std::__ndk1::__shared_ptr_emplace<kev::TaskSlot, std::__ndk1::allocator<kev::TaskSlot> >'; recompile with -fPIC
>>> defined in /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a(EventLoopImpl.cpp.o)
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::appendTask(std::__ndk1::function<void ()>, kev::EventLoop::Token::Impl*, char const*)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for kev::TaskSlot'; recompile with -fPIC
>>> defined in /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a(EventLoopImpl.cpp.o)
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::appendTask(std::__ndk1::function<void ()>, kev::EventLoop::Token::Impl*, char const*)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for std::__ndk1::__shared_ptr_emplace<kev::DelayedTaskSlot, std::__ndk1::allocator<kev::DelayedTaskSlot> >'; recompile with -fPIC
>>> defined in /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a(EventLoopImpl.cpp.o)
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::EventLoop::Impl::appendDelayedTask(unsigned int, std::__ndk1::function<void ()>, kev::EventLoop::Token::Impl*, char const*)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: relocation R_ARM_REL32 cannot be used against symbol 'vtable for kev::TaskSlot'; recompile with -fPIC
>>> defined in /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a(EventLoopImpl.cpp.o)
>>> referenced by EventLoopImpl.cpp
>>>               EventLoopImpl.cpp.o:(kev::DelayedTaskSlot::DelayedTaskSlot(kev::EventLoop::Impl*, std::__ndk1::function<void ()>&&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> >)) in archive /root/code/kuma/third_party/libkev/lib/android/armeabi-v7a/libkev.a

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../../../../bin/android/armeabi-v7a/libkuma.so] 错误 1
make[1]: *** [CMakeFiles/kuma.dir/all] 错误 2

**Comment by Jamol** [comment]
I'll reimplement android API with kotlin, corrently the WebSocket API is completed, please try it.
