### ISSUE TITLE
wss can't receive data

### ISSUE THREAD

**Issue by hhq163** [Jamol/kuma#6]
hello Jamol,
      I run the test demo as a wss server:
./server wss://0.0.0.0:6086

     and use a webpage to send a wss request:
wss://192.168.31.232:6086
after handshake ,I send a message(binary data),it returned: (Opcode -1).The server log shows:

INFO: [140191080888384] AcceptorBase_2:: onAccept, fd=16, peer_ip=192.168.31.147, peer_port=50079
TcpServer::onAccept, fd=16, ip=192.168.31.147, port=50079, proto=5
INFO: [140190551111424] TcpSocket_15:: attachFd, fd=16, flags=1
INFO: [140190551111424] SocketBase_16:: attachFd, fd=16, state=0
INFO: [140190551111424] EPoll::registerFd, fd=16, ev=2147483677
INFO: [140190551111424] TcpSocket_15:: startSslHandshake, ssl_role=1, fd=16
INFO: [140190551111424] SioHandler_16:: handshake, success, fd=16
INFO: [140190551111424] TcpSocket_15:: checkSslHandshake, completed, err=0
INFO: [140190551111424] WebSocket_14:: onStateOpen
ERROR: [140190551111424] SioHandler_16:: receive, SSL_read failed, fd=16, ssl_status=0, ssl_err=5, os_err=0, err_msg=
INFO: [140190551111424] SocketBase_16:: close, state=3
INFO: [140190551111424] EPoll::unregisterFd, fd=16, max_fd=1023
INFO: [140190551111424] TcpSocket_15:: close
INFO: [140190551111424] WebSocket_14:: onError, err=-9

it can't receive msg from SSL_read function, I anlysysed the ssl_err,it just say,SSL_ERROR_SYSCALL,it's a bottom error.  I can't find the answer, hope to get help from you.

you can contact me with email:hhq163@gmail.com

**Comment by hhq163** [comment]
I use the openssl-1.0.2j version,is there any problem for this version?

**Comment by Jamol** [comment]
Hi, @hhq163 
    Do you configure the cert correctly? please make sure 1) your cert is issued to  192.168.31.232. 2)  you had add your CAs' certs to trusted cert store.

   you can run kuma test server to verify it: copy kuma/test/www to server binary folder, run server on autos://0.0.0.0:6086, then open the test URL https://127.0.0.1:6086 on your browser, and ignore the security warning and visit the site, you'll see kuma test page, click the test WebSocket to check if it works.
