### ISSUE TITLE
http/2.0 testing connection reuse ...request failed..

### ISSUE THREAD

**Issue by jch2001** [Jamol/kuma#7]
hi,
i tryed test http/2.0 request in connection reuse case...

first request has success..
but second request has failed.. 
>
HttpRequest::Impl::sendRequest() return -2  ( INVALID_STATE ) 
code is IDLE or WAIT_FOR_REUSE case  success ... current state::COMPLETE ...

what' wrong??

**Comment by Jamol** [comment]
Hi @jch2001 
   Do you call the HttpRequest::reset()? 
   currently the HttpRequest::reset() needs to be called for HTTP reuse. Next I'll enhance it.

**Comment by jch2001** [comment]
of cause.. 
i  did HttpRequest::reset()  call complete event callback..
testing HTTP1.1 no problem... only HTTP/2.0 has problem..

**Comment by Jamol** [comment]
Thanks for your info, will test it later

**Comment by Jamol** [comment]
fixed
