### ISSUE TITLE
linux compile error - http2 reuse bug patch version

### ISSUE THREAD

**Issue by jch2001** [Jamol/kuma#8]
hi...

i just download & compile souce.. 
but compile failed..
-------------------------------------------------------------------
kmapi.cpp: In constructor ‘kuma::EventLoop::EventLoop(kuma::PollType)’:
kmapi.cpp:79:43: error: call of overloaded ‘ImplHelper(kuma::PollType&)’ is ambiguous
     auto h = new EventLoopHelper(poll_type);
                                           ^
kmapi.cpp:79:43: note: candidates are:
kmapi.cpp:60:5: note: kuma::ImplHelper<Impl>::ImplHelper(Args&& ...) [with Args = {kuma::PollType&}; Impl = kuma::EventLoop::Impl]
     ImplHelper(Args&&... args)
     ^
kmapi.cpp:53:5: note: kuma::ImplHelper<Impl>::ImplHelper(Args& ...) [with Args = {kuma::PollType}; Impl = kuma::EventLoop::Impl]
     ImplHelper(Args&... args)
     ^
kmapi.cpp:47:8: note: kuma::ImplHelper<kuma::EventLoop::Impl>::ImplHelper(const kuma::ImplHelper<kuma::EventLoop::Impl>&) <deleted>
 struct ImplHelper {
        ^
kmapi.cpp:47:8: note: kuma::ImplHelper<kuma::EventLoop::Impl>::ImplHelper(kuma::ImplHelper<kuma::EventLoop::Impl>&&) <deleted>
make: *** [../objs/linux/kmapi.o] error 1
[pgfe@pgfe1:/UDC/INFRA/OpenLib/KUMA/kuma-master/src]

**Comment by jch2001** [comment]
compiled  linux platform... and failed..

**Comment by Jamol** [comment]
sorry, the patch includes an unnecessary change, will rollback it.

**Comment by Jamol** [comment]
fixed
